name: Monitor Cron
on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행 (GitHub Actions 최소 간격)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check current time
        run: |
          echo "Current UTC time: $(date -u)"
          echo "Current local time: $(date)"
          echo "GitHub Actions environment:"
          echo "  - GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "  - GITHUB_SHA: ${{ github.sha }}"
          echo "  - GITHUB_REF: ${{ github.ref }}"
      
      - name: Test API connection
        run: |
          echo "Testing basic connectivity..."
          curl -I https://non-sleep.vercel.app/api/ping
          echo ""
          
      - name: Call Monitor API with POST
        run: |
          echo "Calling scheduler API..."
          response=$(curl -s -X POST https://non-sleep.vercel.app/api/scheduler/run \
            -H "Content-Type: application/json" \
            -d '{
              "source": "github-actions",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
              "environment": "production",
              "trigger": "scheduled"
            }')
          
          echo "API Response:"
          echo "$response"
          
          # 응답 확인
          if echo "$response" | grep -q '"ok":true'; then
            echo "✅ API call successful"
          else
            echo "❌ API call failed"
            exit 1
          fi
